default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: desafio_dev_development

test:
  <<: *default
  database: desafio_dev_test

production:
  <<: *default
  database: desafio_dev_production
  username: desafio_dev
  password: <%= ENV['DESAFIO_DEV_DATABASE_PASSWORD'] %>
